spring:
  datasource1:
    url: jdbc:sqlserver://localhost;databaseName=application
    username: SA
    password: PointBlank10
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  datasource2:
    url: jdbc:sqlserver://localhost;databaseName=security
    username: SA
    password: PointBlank10
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show_sql:
      hibernate:
        ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: sql_server
